config/routes.rb
RailsTest::Application.routes.draw do

  match 'click_thrus/clicked'
  resources :click_thrus

  resources :page_views

  match 'schedule_promos/populate'
  match 'schedule_promos/clear_future'
  match 'schedule_promos/clear_all'
  match 'schedule_promos/more_games'
   
  resources :schedule_promos
  

  resources :round_robin_promos

  resources :promos

  resources :apps

end

app/controllers/page_views_controller.rb
class PageViewsController < ApplicationController
  # GET /page_views
  # GET /page_views.json
  def index
    @page_views = PageView.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @page_views }
    end
  end

  # GET /page_views/1
  # GET /page_views/1.json
  def show
    @page_view = PageView.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page_view }
    end
  end

  # GET /page_views/new
  # GET /page_views/new.json
  def new
    @page_view = PageView.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page_view }
    end
  end

  # GET /page_views/1/edit
  def edit
    @page_view = PageView.find(params[:id])
  end

  # POST /page_views
  # POST /page_views.json
  def create
    @page_view = PageView.new(params[:page_view])

    respond_to do |format|
      if @page_view.save
        format.html { redirect_to @page_view, notice: 'Page view was successfully created.' }
        format.json { render json: @page_view, status: :created, location: @page_view }
      else
        format.html { render action: "new" }
        format.json { render json: @page_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /page_views/1
  # PUT /page_views/1.json
  def update
    @page_view = PageView.find(params[:id])

    respond_to do |format|
      if @page_view.update_attributes(params[:page_view])
        format.html { redirect_to @page_view, notice: 'Page view was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /page_views/1
  # DELETE /page_views/1.json
  def destroy
    @page_view = PageView.find(params[:id])
    @page_view.destroy

    respond_to do |format|
      format.html { redirect_to page_views_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/page_views_helper.rb
module PageViewsHelper
end

app/views/page_views/_form.html.erb
<%= form_for(@page_view) do |f| %>
  <% if @page_view.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page_view.errors.count, "error") %> prohibited this page_view from being saved:</h2>

      <ul>
      <% @page_view.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_area :url %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.datetime_select :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/page_views/edit.html.erb
<h1>Editing page_view</h1>

<%= render 'form' %>

<%= link_to 'Show', @page_view %> |
<%= link_to 'Back', page_views_path %>

app/views/page_views/index.html.erb
<h1>Listing page_views</h1>

<table>
  <tr>
    <th>Url</th>
    <th>Time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @page_views.each do |page_view| %>
  <tr>
    <td><%= page_view.url %></td>
    <td><%= page_view.time %></td>
    <td><%= link_to 'Show', page_view %></td>
    <td><%= link_to 'Edit', edit_page_view_path(page_view) %></td>
    <td><%= link_to 'Destroy', page_view, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page view', new_page_view_path %>

app/views/page_views/new.html.erb
<h1>New page_view</h1>

<%= render 'form' %>

<%= link_to 'Back', page_views_path %>

app/views/page_views/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @page_view.url %>
</p>

<p>
  <b>Time:</b>
  <%= @page_view.time %>
</p>


<%= link_to 'Edit', edit_page_view_path(@page_view) %> |
<%= link_to 'Back', page_views_path %>