config/routes.rb
RailsTest::Application.routes.draw do

  match 'click_thrus/clicked'
  resources :click_thrus

  resources :page_views

  match 'schedule_promos/populate'
  match 'schedule_promos/clear_future'
  match 'schedule_promos/clear_all'
  match 'schedule_promos/more_games'
   
  resources :schedule_promos
  

  resources :round_robin_promos

  resources :promos

  resources :apps

end

app/models/promo.rb
class Promo < ActiveRecord::Base
  attr_accessible :name
  validates :name, :uniqueness => true, :presence => true
end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
  # GET /promos
  # GET /promos.json
  def index
    @promos = Promo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @promos }
    end
  end

  # GET /promos/1
  # GET /promos/1.json
  def show
    @promo = Promo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @promo }
    end
  end

  # GET /promos/new
  # GET /promos/new.json
  def new
    @promo = Promo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @promo }
    end
  end

  # GET /promos/1/edit
  def edit
    @promo = Promo.find(params[:id])
  end

  # POST /promos
  # POST /promos.json
  def create
    @promo = Promo.new(params[:promo])

    respond_to do |format|
      if @promo.save
        format.html { redirect_to @promo, notice: 'Promo was successfully created.' }
        format.json { render json: @promo, status: :created, location: @promo }
      else
        format.html { render action: "new" }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /promos/1
  # PUT /promos/1.json
  def update
    @promo = Promo.find(params[:id])

    respond_to do |format|
      if @promo.update_attributes(params[:promo])
        format.html { redirect_to @promo, notice: 'Promo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promos/1
  # DELETE /promos/1.json
  def destroy
    @promo = Promo.find(params[:id])
    @promo.destroy

    respond_to do |format|
      format.html { redirect_to promos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/views/promos/_form.html.erb
<%= form_for(@promo) do |f| %>
  <% if @promo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@promo.errors.count, "error") %> prohibited this promo from being saved:</h2>

      <ul>
      <% @promo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/promos/edit.html.erb
<h1>Editing promo</h1>

<%= render 'form' %>

<%= link_to 'Show', @promo %> |
<%= link_to 'Back', promos_path %>

app/views/promos/index.html.erb
<h1>Listing promos</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @promos.each do |promo| %>
  <tr>
    <td><%= promo.name %></td>
    <td><%= link_to 'Show', promo %></td>
    <td><%= link_to 'Edit', edit_promo_path(promo) %></td>
    <td><%= link_to 'Destroy', promo, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Promo', new_promo_path %>

app/views/promos/new.html.erb
<h1>New promo</h1>

<%= render 'form' %>

<%= link_to 'Back', promos_path %>

app/views/promos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @promo.name %>
</p>


<%= link_to 'Edit', edit_promo_path(@promo) %> |
<%= link_to 'Back', promos_path %>