config/routes.rb
RailsTest::Application.routes.draw do

  match 'click_thrus/clicked'
  resources :click_thrus

  resources :page_views

  match 'schedule_promos/populate'
  match 'schedule_promos/clear_future'
  match 'schedule_promos/clear_all'
  match 'schedule_promos/more_games'
   
  resources :schedule_promos
  

  resources :round_robin_promos

  resources :promos

  resources :apps

end

app/models/schedule_promo.rb
class SchedulePromo < ActiveRecord::Base
  attr_accessible :app_id, :promo_id, :start_time, :stop_time

  belongs_to :app
  belongs_to :promo
end

app/controllers/schedule_promos_controller.rb
class SchedulePromosController < ApplicationController

  protect_from_forgery :except => :populate
  # GET /schedule_promos
  # GET /schedule_promos.json
  def index
    @schedule_promos = SchedulePromo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schedule_promos }
    end
  end

  def more_games
     @schedule_promo = SchedulePromo.find(:last, :order => "start_time ASC", :conditions => ['start_time < ? AND stop_time > ?', Time.now.to_i, Time.now.to_i])

    @page_view = PageView.new(:url => "http://#{request.host}:#{request.port}#{request.fullpath}", :time => Time.now.to_i)
    @page_view.save()
    
    #@schedule_promo = SchedulePromo.find(:last, :order => "start_time ASC")
     if @schedule_promo == nil
      @schedule_promo = SchedulePromo.find(:last, :order => "start_time ASC")
    end

    

    puts(@schedule_promo.inspect)
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @schedule_promo }
    end
  end

  def clear_future
    @future_scheduled_promos = SchedulePromo.find(:all, :conditions => ['start_time > ?', Time.now.to_i])
    @future_scheduled_promos.each{|e| e.destroy}
    redirect_to :action => "index"
  end

  def clear_all
    @future_scheduled_promos = SchedulePromo.find(:all)
    @future_scheduled_promos.each{|e| e.destroy}
    redirect_to :action => "index"
  end
  
  def populate

    time = Time.now.to_i
    projectedFuture = time + (5 *60)
    
    @round_robin = RoundRobinPromo.find(:all, :order => "position")

    while(time < projectedFuture)
    @round_robin.each { |elem|
      @schedule_promo = SchedulePromo.new(:app_id => elem.app_id, :promo_id => elem.promo_id, :start_time => time, :stop_time => time + elem.duration)
      time = @schedule_promo.stop_time
      @schedule_promo.save()
    }
    end

    redirect_to :action => "index"

    
  end

  # GET /schedule_promos/1
  # GET /schedule_promos/1.json
  def show
    @schedule_promo = SchedulePromo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @schedule_promo }
    end
  end

  # GET /schedule_promos/new
  # GET /schedule_promos/new.json
  def new
    @schedule_promo = SchedulePromo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @schedule_promo }
    end
  end

  # GET /schedule_promos/1/edit
  def edit
    @schedule_promo = SchedulePromo.find(params[:id])
  end

  # POST /schedule_promos
  # POST /schedule_promos.json
  def create
    @schedule_promo = SchedulePromo.new(params[:schedule_promo])

    respond_to do |format|
      if @schedule_promo.save
        format.html { redirect_to @schedule_promo, notice: 'Schedule promo was successfully created.' }
        format.json { render json: @schedule_promo, status: :created, location: @schedule_promo }
      else
        format.html { render action: "new" }
        format.json { render json: @schedule_promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schedule_promos/1
  # PUT /schedule_promos/1.json
  def update
    @schedule_promo = SchedulePromo.find(params[:id])

    respond_to do |format|
      if @schedule_promo.update_attributes(params[:schedule_promo])
        format.html { redirect_to @schedule_promo, notice: 'Schedule promo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @schedule_promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedule_promos/1
  # DELETE /schedule_promos/1.json
  def destroy
    @schedule_promo = SchedulePromo.find(params[:id])
    @schedule_promo.destroy

    respond_to do |format|
      format.html { redirect_to schedule_promos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/schedule_promos_helper.rb
module SchedulePromosHelper
end

app/views/schedule_promos/_form.html.erb
<%= form_for(@schedule_promo) do |f| %>
  <% if @schedule_promo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule_promo.errors.count, "error") %> prohibited this schedule_promo from being saved:</h2>

      <ul>
      <% @schedule_promo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :stop_time %><br />
    <%= f.datetime_select :stop_time %>
  </div>
  <div class="field">
    <%= f.label :app_id %><br />
    <%= f.number_field :app_id %>
  </div>
  <div class="field">
    <%= f.label :promo_id %><br />
    <%= f.number_field :promo_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedule_promos/edit.html.erb
<h1>Editing schedule_promo</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule_promo %> |
<%= link_to 'Back', schedule_promos_path %>

app/views/schedule_promos/index.html.erb
<h1>Listing schedule_promos</h1>
<h2>The current unix timestamp is <%= currentTime = Time.now.to_i %></h2>
<h3 class = "past">Promotions of the past</h3>
<h3 class = "present">Promotion of the present. </h3>
<h3 class = "future">Promotions yet to come</h3>

<table>
  <tr>
    <th>Start time</th>
    <th>Stop time</th>
    <th>App</th>
    <th>Promo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @schedule_promos.each do |schedule_promo| %>

    <% if (currentTime >= schedule_promo.start_time) %>
    <% cssClass = "past" %>
    <% elsif (currentTime.between?(schedule_promo.start_time, schedule_promo.stop_time)) %>
    <% cssClass = "present" %>
    <% else %>
    <% cssClass = "future" %>
    <% end %>

    
  <tr class = "<%= cssClass %>">


    
    <td ><%= schedule_promo.start_time %></td>
    <td><%= schedule_promo.stop_time %></td>
    <td><%= schedule_promo.app.name %></td>
    <td><%= schedule_promo.promo.name %></td>
    <td><%= link_to 'Show', schedule_promo %></td>
    <td><%= link_to 'Edit', edit_schedule_promo_path(schedule_promo) %></td>
    <td><%= link_to 'Destroy', schedule_promo, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Schedule promo', new_schedule_promo_path %>
</p><%= link_to 'Clear the future schedule', :controller => "schedule_promos", :action => "clear_future" %>
</p><%= link_to 'Clear all', :controller => "schedule_promos", :action => "clear_all" %>
</p><%= link_to 'Populate the schedule', :controller => "schedule_promos", :action => "populate" %>

app/views/schedule_promos/moreGames.html.erb
hellow orld

app/views/schedule_promos/more_games.html.erb
<% if @schedule_promo == nil %>
No promotion was found
<% else %>
This would be a promotion for the app <b> <%= @schedule_promo.app.name %> </b>
<p> rendered in the style of promo <b> <%= @schedule_promo.promo.name %> </b>
<%end%>

<p> <%= link_to 'Click thru to the app promoted', :controller => :click_thrus, :action => :clicked %>

app/views/schedule_promos/new.html.erb
<h1>New schedule_promo</h1>

<%= render 'form' %>

<%= link_to 'Back', schedule_promos_path %>

app/views/schedule_promos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Start time:</b>
  <%= @schedule_promo.start_time %>
</p>

<p>
  <b>Stop time:</b>
  <%= @schedule_promo.stop_time %>
</p>

<p>
  <b>App:</b>
  <%= @schedule_promo.app_id %>
</p>

<p>
  <b>Promo:</b>
  <%= @schedule_promo.promo_id %>
</p>


<%= link_to 'Edit', edit_schedule_promo_path(@schedule_promo) %> |
<%= link_to 'Back', schedule_promos_path %>